### PR TITLE
travis: add post_install hook compiling the examples, test on 4.05.0 and 4.06.0

### PR DESCRIPTION
**Pull request by hannesm**
as an update for #85

### CODE REVIEW

**Comment by hannesm** [comment]
```
File "examples/hello_async.ml", line 1, characters 5-13:
Warning 3: deprecated: module Core.Std
[since 2017-02] Use Core. The Std sub-module is no longer needed
File "examples/hello_async.ml", line 2, characters 5-14:
Error: Unbound module Async.Std
```

seems like your `hello_async` needs some updating..

**Comment by hannesm** [comment]
oh, and btw, I tried only a `jbuilder build ..hello_lwt.exe`, but this already asked me to install `async`.  is there a way to have this only needing `lwt` and `cohttp-lwt-unix` (I worked around this by manually removing the last block of the `examples/jbuild` file)?

**Comment by hannesm** [comment]
(I commented the `hello_async` example out for now to make travis happy, all green now) 😄

**Comment by seliopou** [comment]
Made #88 to address the build error for the async example. I'll merge that and then this should be fine to merge without commenting out the async example.

**Comment by hannesm** [comment]
@seliopou ok, force-pushed this branch after `git reset --hard HEAD~1`, thus you can restart travis and merge once #88 is in :)

**Comment by seliopou** [comment]
Thanks!

**Pull request merged**
