### PR TITLE
Convert example to Lwt

### PR DESCRIPTION
**Pull request by michipili**
I quickly converted the async example to lwt_unix.

### CODE REVIEW

**Comment by seliopou** [comment]
This is great! and much appreciated. While you're at it could you add an `Executable` section to the `_oasis` file for this example?

**Comment by michipili** [comment]
I am not familiar with oasis (I use [bsdowl](https://github.com/michipili/bsdowl)) so it is probably better if you double-check my prose. :)  I hope the example will help other users to getting started with Webmaschine.

BTW are you planning to move Travis CI to the newest infrastructure? I made this in all my projects and I described the procedure on [my blog](http://unix-workstation.blogspot.de/2015/08/opam-and-bsd-owl-support-for-travis-ci.html) so I could help there too.

**Comment by seliopou** [comment]
I've been thinking about using container-based builds for various projects, but this one builds so quickly that it's not a huge priority.

**Comment by michipili** [comment]
So this should be fine now, but maybe you found something more in between?

**Comment by seliopou** [comment]
Build failed due to network issues. I just restarted it.

**Comment by michipili** [comment]
> Build failed due to network issues. I just restarted it.

This is mostly why I moved the CI suite to the container infrastructure, I bet Travis do not put much energy in the old one. :)

**Pull request merged**
